version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: app
    ports: 
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d